---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "docker/python-ansible"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "docker/python-tox"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"  # See https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#directory
    schedule:
      interval: "weekly"
